export const schema = [
	{
		key: 'evaluate',
		type: 1,
		text: '好评',
		active: false,
		expansion: false,
		value: '',
	},
	{
		key: 'price',
		type: 2,
		text: '价格',
		active: false,
		expansion: false,
		value: '',
	},
	{
		key: 'grade',
		type: 3,
		text: '等级',
		active: false,
		expansion: false,
		value: '',
		subCondition: ['A', 'B', 'C', 'D'].map((t) => ({
			key: 'grade-' + t,
			text: t + '级',
			active: false,
		})),
	},
	{
		key: 'filtrate',
		type: 4,
		text: '筛选',
		active: false,
		expansion: false,
		value: '',
		subCondition: [
			{
				key: 'flaw',
				subText: '瑕疵',
				subCondition: [
					'成熟度开',
					'枝条不匀',
					'轻微夹支',
					'1-3枝夹支',
					'枝条带拐',
					'轻微色差',
					'轻微白粉',
					'花头大小不均',
					'轻微黄叶',
				].map((t) => ({ key: t, text: t, active: false })),
			},
			{
				key: 'length',
				subText: '长度',
				subCondition: [
					'55CM',
					'70CM',
					'65CM',
					'60CM',
					'50CM',
					'45CM',
					'35CM',
					'40CM',
					'30CM',
				].map((t) => ({ key: t, text: t, active: false })),
			},
		],
	},
];
