/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/amap/control': RouteRecordInfo<
      '/amap/control',
      '/amap/control',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/amap/coverage': RouteRecordInfo<
      '/amap/coverage',
      '/amap/coverage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/amap/get-address': RouteRecordInfo<
      '/amap/get-address',
      '/amap/get-address',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/amap/init': RouteRecordInfo<
      '/amap/init',
      '/amap/init',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/amap/marker': RouteRecordInfo<
      '/amap/marker',
      '/amap/marker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/amap/marker(custom)': RouteRecordInfo<
      '/amap/marker(custom)',
      '/amap/marker(custom)',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/amap/marker(text)': RouteRecordInfo<
      '/amap/marker(text)',
      '/amap/marker(text)',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/amap/theme': RouteRecordInfo<
      '/amap/theme',
      '/amap/theme',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bmap/6.area': RouteRecordInfo<
      '/bmap/6.area',
      '/bmap/6/area',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bmap/7.get_address(lon_lat)': RouteRecordInfo<
      '/bmap/7.get_address(lon_lat)',
      '/bmap/7/get_address(lon_lat)',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bmap/control': RouteRecordInfo<
      '/bmap/control',
      '/bmap/control',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bmap/get_lon_lat': RouteRecordInfo<
      '/bmap/get_lon_lat',
      '/bmap/get_lon_lat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bmap/init': RouteRecordInfo<
      '/bmap/init',
      '/bmap/init',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bmap/marker': RouteRecordInfo<
      '/bmap/marker',
      '/bmap/marker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bmap/type': RouteRecordInfo<
      '/bmap/type',
      '/bmap/type',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css_/attr_con': RouteRecordInfo<
      '/css_/attr_con',
      '/css_/attr_con',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css_/framework': RouteRecordInfo<
      '/css_/framework',
      '/css_/framework',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css_/position': RouteRecordInfo<
      '/css_/position',
      '/css_/position',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css_/props_select': RouteRecordInfo<
      '/css_/props_select',
      '/css_/props_select',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css_/pseudo_class': RouteRecordInfo<
      '/css_/pseudo_class',
      '/css_/pseudo_class',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css_/pseudo_class_a': RouteRecordInfo<
      '/css_/pseudo_class_a',
      '/css_/pseudo_class_a',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css_/pseudo_class_befor_after': RouteRecordInfo<
      '/css_/pseudo_class_befor_after',
      '/css_/pseudo_class_befor_after',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css_/pseudo_class_befor_marker_selection_line_letter': RouteRecordInfo<
      '/css_/pseudo_class_befor_marker_selection_line_letter',
      '/css_/pseudo_class_befor_marker_selection_line_letter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css_/pseudo_class_checked': RouteRecordInfo<
      '/css_/pseudo_class_checked',
      '/css_/pseudo_class_checked',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css_/pseudo_class_child': RouteRecordInfo<
      '/css_/pseudo_class_child',
      '/css_/pseudo_class_child',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css_/pseudo_class_enabled': RouteRecordInfo<
      '/css_/pseudo_class_enabled',
      '/css_/pseudo_class_enabled',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css_/pseudo_class_focus': RouteRecordInfo<
      '/css_/pseudo_class_focus',
      '/css_/pseudo_class_focus',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css_/pseudo_class_focus_within': RouteRecordInfo<
      '/css_/pseudo_class_focus_within',
      '/css_/pseudo_class_focus_within',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css_/pseudo_class_has+': RouteRecordInfo<
      '/css_/pseudo_class_has+',
      '/css_/pseudo_class_has+',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css_/pseudo_class_not_has': RouteRecordInfo<
      '/css_/pseudo_class_not_has',
      '/css_/pseudo_class_not_has',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css_/pseudo_class_only': RouteRecordInfo<
      '/css_/pseudo_class_only',
      '/css_/pseudo_class_only',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css_/pseudo_class_required': RouteRecordInfo<
      '/css_/pseudo_class_required',
      '/css_/pseudo_class_required',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css_/pseudo_class_type': RouteRecordInfo<
      '/css_/pseudo_class_type',
      '/css_/pseudo_class_type',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css_/pseudo_class_valid': RouteRecordInfo<
      '/css_/pseudo_class_valid',
      '/css_/pseudo_class_valid',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css_/sequence': RouteRecordInfo<
      '/css_/sequence',
      '/css_/sequence',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css_/toggle_btn': RouteRecordInfo<
      '/css_/toggle_btn',
      '/css_/toggle_btn',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css_/vis-a-vis': RouteRecordInfo<
      '/css_/vis-a-vis',
      '/css_/vis-a-vis',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/address_resolution': RouteRecordInfo<
      '/demo/address_resolution',
      '/demo/address_resolution',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/calendar': RouteRecordInfo<
      '/demo/calendar',
      '/demo/calendar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/dingding': RouteRecordInfo<
      '/demo/dingding',
      '/demo/dingding',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/dom_to_img': RouteRecordInfo<
      '/demo/dom_to_img',
      '/demo/dom_to_img',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/goods_car': RouteRecordInfo<
      '/demo/goods_car',
      '/demo/goods_car',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/goods_spec': RouteRecordInfo<
      '/demo/goods_spec',
      '/demo/goods_spec',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/grape': RouteRecordInfo<
      '/demo/grape',
      '/demo/grape',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/img_base64': RouteRecordInfo<
      '/demo/img_base64',
      '/demo/img_base64',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/monaco-editor': RouteRecordInfo<
      '/demo/monaco-editor',
      '/demo/monaco-editor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/qr_code': RouteRecordInfo<
      '/demo/qr_code',
      '/demo/qr_code',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/scan-code': RouteRecordInfo<
      '/demo/scan-code',
      '/demo/scan-code',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/short_video': RouteRecordInfo<
      '/demo/short_video',
      '/demo/short_video',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/spark-ai': RouteRecordInfo<
      '/demo/spark-ai',
      '/demo/spark-ai',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/spin_swiper': RouteRecordInfo<
      '/demo/spin_swiper',
      '/demo/spin_swiper',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/taskbar-transition-animation': RouteRecordInfo<
      '/demo/taskbar-transition-animation',
      '/demo/taskbar-transition-animation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/to_chinese_number': RouteRecordInfo<
      '/demo/to_chinese_number',
      '/demo/to_chinese_number',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/viewport-transition': RouteRecordInfo<
      '/demo/viewport-transition',
      '/demo/viewport-transition',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/echarts/basics': RouteRecordInfo<
      '/echarts/basics',
      '/echarts/basics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/echarts/horizontal_column_chart': RouteRecordInfo<
      '/echarts/horizontal_column_chart',
      '/echarts/horizontal_column_chart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/echarts/map_of_china': RouteRecordInfo<
      '/echarts/map_of_china',
      '/echarts/map_of_china',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/echarts/qujin': RouteRecordInfo<
      '/echarts/qujin',
      '/echarts/qujin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/echarts/series': RouteRecordInfo<
      '/echarts/series',
      '/echarts/series',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/echarts/sort': RouteRecordInfo<
      '/echarts/sort',
      '/echarts/sort',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/echarts/title&position': RouteRecordInfo<
      '/echarts/title&position',
      '/echarts/title&position',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/echarts/weather': RouteRecordInfo<
      '/echarts/weather',
      '/echarts/weather',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/echarts/wordcloud': RouteRecordInfo<
      '/echarts/wordcloud',
      '/echarts/wordcloud',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/echarts/xaxis': RouteRecordInfo<
      '/echarts/xaxis',
      '/echarts/xaxis',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/echarts/yaxis': RouteRecordInfo<
      '/echarts/yaxis',
      '/echarts/yaxis',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/es6/array-buffer': RouteRecordInfo<
      '/es6/array-buffer',
      '/es6/array-buffer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/es6/Iterator': RouteRecordInfo<
      '/es6/Iterator',
      '/es6/Iterator',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/es6/let': RouteRecordInfo<
      '/es6/let',
      '/es6/let',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/es6/promise': RouteRecordInfo<
      '/es6/promise',
      '/es6/promise',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/es6/proxy&reflect': RouteRecordInfo<
      '/es6/proxy&reflect',
      '/es6/proxy&reflect',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/es6/set&map': RouteRecordInfo<
      '/es6/set&map',
      '/es6/set&map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/es6/symbol': RouteRecordInfo<
      '/es6/symbol',
      '/es6/symbol',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/es6/变量的解构赋值': RouteRecordInfo<
      '/es6/变量的解构赋值',
      '/es6/变量的解构赋值',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/es6/字符串新增方法': RouteRecordInfo<
      '/es6/字符串新增方法',
      '/es6/字符串新增方法',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/es6/对象扩展': RouteRecordInfo<
      '/es6/对象扩展',
      '/es6/对象扩展',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/es6/数组扩展': RouteRecordInfo<
      '/es6/数组扩展',
      '/es6/数组扩展',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/es6/编程风格': RouteRecordInfo<
      '/es6/编程风格',
      '/es6/编程风格',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/js_/btoa': RouteRecordInfo<
      '/js_/btoa',
      '/js_/btoa',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/js_/geolocation': RouteRecordInfo<
      '/js_/geolocation',
      '/js_/geolocation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/js_/stop-array-foreach': RouteRecordInfo<
      '/js_/stop-array-foreach',
      '/js_/stop-array-foreach',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/js_/string': RouteRecordInfo<
      '/js_/string',
      '/js_/string',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/js_/window-api': RouteRecordInfo<
      '/js_/window-api',
      '/js_/window-api',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/less/&': RouteRecordInfo<
      '/less/&',
      '/less/&',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/less/function': RouteRecordInfo<
      '/less/function',
      '/less/function',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/less/gridding': RouteRecordInfo<
      '/less/gridding',
      '/less/gridding',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/less/hover_effect_1': RouteRecordInfo<
      '/less/hover_effect_1',
      '/less/hover_effect_1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/less/if': RouteRecordInfo<
      '/less/if',
      '/less/if',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/less/inherit': RouteRecordInfo<
      '/less/inherit',
      '/less/inherit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/less/list': RouteRecordInfo<
      '/less/list',
      '/less/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/less/math': RouteRecordInfo<
      '/less/math',
      '/less/math',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/less/mixin': RouteRecordInfo<
      '/less/mixin',
      '/less/mixin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/less/props-merge': RouteRecordInfo<
      '/less/props-merge',
      '/less/props-merge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/less/var': RouteRecordInfo<
      '/less/var',
      '/less/var',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/motion/eg': RouteRecordInfo<
      '/motion/eg',
      '/motion/eg',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/scss/annotation': RouteRecordInfo<
      '/scss/annotation',
      '/scss/annotation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/scss/each': RouteRecordInfo<
      '/scss/each',
      '/scss/each',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/scss/for': RouteRecordInfo<
      '/scss/for',
      '/scss/for',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/scss/if&for': RouteRecordInfo<
      '/scss/if&for',
      '/scss/if&for',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/scss/mix-in': RouteRecordInfo<
      '/scss/mix-in',
      '/scss/mix-in',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/scss/mixin': RouteRecordInfo<
      '/scss/mixin',
      '/scss/mixin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/scss/random-color': RouteRecordInfo<
      '/scss/random-color',
      '/scss/random-color',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/scss/var': RouteRecordInfo<
      '/scss/var',
      '/scss/var',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/scss/while': RouteRecordInfo<
      '/scss/while',
      '/scss/while',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/scss/占位符百分号': RouteRecordInfo<
      '/scss/占位符百分号',
      '/scss/占位符百分号',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/scss/属性嵌套': RouteRecordInfo<
      '/scss/属性嵌套',
      '/scss/属性嵌套',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/scss/继承': RouteRecordInfo<
      '/scss/继承',
      '/scss/继承',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/swiper/base': RouteRecordInfo<
      '/swiper/base',
      '/swiper/base',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/three-js/amf': RouteRecordInfo<
      '/three-js/amf',
      '/three-js/amf',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/three-js/axis': RouteRecordInfo<
      '/three-js/axis',
      '/three-js/axis',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/three-js/base': RouteRecordInfo<
      '/three-js/base',
      '/three-js/base',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/three-js/first': RouteRecordInfo<
      '/three-js/first',
      '/three-js/first',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/three-js/hdr': RouteRecordInfo<
      '/three-js/hdr',
      '/three-js/hdr',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/three-js/obj': RouteRecordInfo<
      '/three-js/obj',
      '/three-js/obj',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/three-js/textureLoader': RouteRecordInfo<
      '/three-js/textureLoader',
      '/three-js/textureLoader',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/async-component': RouteRecordInfo<
      '/vue/async-component',
      '/vue/async-component',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/built-in_comp_transition': RouteRecordInfo<
      '/vue/built-in_comp_transition',
      '/vue/built-in_comp_transition',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/built-in_comp-keep-alive': RouteRecordInfo<
      '/vue/built-in_comp-keep-alive',
      '/vue/built-in_comp-keep-alive',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/built-in_comp-teleport': RouteRecordInfo<
      '/vue/built-in_comp-teleport',
      '/vue/built-in_comp-teleport',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/built-in_comp-transitiongroup': RouteRecordInfo<
      '/vue/built-in_comp-transitiongroup',
      '/vue/built-in_comp-transitiongroup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/class_style': RouteRecordInfo<
      '/vue/class_style',
      '/vue/class_style',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/comp_message_parent_child': RouteRecordInfo<
      '/vue/comp_message_parent_child',
      '/vue/comp_message_parent_child',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/comp_message_v-model': RouteRecordInfo<
      '/vue/comp_message_v-model',
      '/vue/comp_message_v-model',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/comp_message-provide': RouteRecordInfo<
      '/vue/comp_message-provide',
      '/vue/comp_message-provide',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/comp_message-ref': RouteRecordInfo<
      '/vue/comp_message-ref',
      '/vue/comp_message-ref',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/component_base': RouteRecordInfo<
      '/vue/component_base',
      '/vue/component_base',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/composable_apis': RouteRecordInfo<
      '/vue/composable_apis',
      '/vue/composable_apis',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/composite_functions': RouteRecordInfo<
      '/vue/composite_functions',
      '/vue/composite_functions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/computed': RouteRecordInfo<
      '/vue/computed',
      '/vue/computed',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/custom_instruction': RouteRecordInfo<
      '/vue/custom_instruction',
      '/vue/custom_instruction',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/event': RouteRecordInfo<
      '/vue/event',
      '/vue/event',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/form_input': RouteRecordInfo<
      '/vue/form_input',
      '/vue/form_input',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/life_cycle': RouteRecordInfo<
      '/vue/life_cycle',
      '/vue/life_cycle',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/list': RouteRecordInfo<
      '/vue/list',
      '/vue/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/modifier': RouteRecordInfo<
      '/vue/modifier',
      '/vue/modifier',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/plug-in': RouteRecordInfo<
      '/vue/plug-in',
      '/vue/plug-in',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/reactive_base': RouteRecordInfo<
      '/vue/reactive_base',
      '/vue/reactive_base',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/reactive_theory': RouteRecordInfo<
      '/vue/reactive_theory',
      '/vue/reactive_theory',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/template': RouteRecordInfo<
      '/vue/template',
      '/vue/template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/template_use': RouteRecordInfo<
      '/vue/template_use',
      '/vue/template_use',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vue/watch': RouteRecordInfo<
      '/vue/watch',
      '/vue/watch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/amap/control.vue': {
      routes:
        | '/amap/control'
      views:
        | never
    }
    'src/views/amap/coverage.vue': {
      routes:
        | '/amap/coverage'
      views:
        | never
    }
    'src/views/amap/get-address.vue': {
      routes:
        | '/amap/get-address'
      views:
        | never
    }
    'src/views/amap/init.vue': {
      routes:
        | '/amap/init'
      views:
        | never
    }
    'src/views/amap/marker.vue': {
      routes:
        | '/amap/marker'
      views:
        | never
    }
    'src/views/amap/marker(custom).vue': {
      routes:
        | '/amap/marker(custom)'
      views:
        | never
    }
    'src/views/amap/marker(text).vue': {
      routes:
        | '/amap/marker(text)'
      views:
        | never
    }
    'src/views/amap/theme.vue': {
      routes:
        | '/amap/theme'
      views:
        | never
    }
    'src/views/bmap/6.area.vue': {
      routes:
        | '/bmap/6.area'
      views:
        | never
    }
    'src/views/bmap/7.get_address(lon_lat).vue': {
      routes:
        | '/bmap/7.get_address(lon_lat)'
      views:
        | never
    }
    'src/views/bmap/control.vue': {
      routes:
        | '/bmap/control'
      views:
        | never
    }
    'src/views/bmap/get_lon_lat.vue': {
      routes:
        | '/bmap/get_lon_lat'
      views:
        | never
    }
    'src/views/bmap/init.vue': {
      routes:
        | '/bmap/init'
      views:
        | never
    }
    'src/views/bmap/marker.vue': {
      routes:
        | '/bmap/marker'
      views:
        | never
    }
    'src/views/bmap/type.vue': {
      routes:
        | '/bmap/type'
      views:
        | never
    }
    'src/views/css_/attr_con.vue': {
      routes:
        | '/css_/attr_con'
      views:
        | never
    }
    'src/views/css_/framework.vue': {
      routes:
        | '/css_/framework'
      views:
        | never
    }
    'src/views/css_/position.vue': {
      routes:
        | '/css_/position'
      views:
        | never
    }
    'src/views/css_/props_select.vue': {
      routes:
        | '/css_/props_select'
      views:
        | never
    }
    'src/views/css_/pseudo_class.vue': {
      routes:
        | '/css_/pseudo_class'
      views:
        | never
    }
    'src/views/css_/pseudo_class_a.vue': {
      routes:
        | '/css_/pseudo_class_a'
      views:
        | never
    }
    'src/views/css_/pseudo_class_befor_after.vue': {
      routes:
        | '/css_/pseudo_class_befor_after'
      views:
        | never
    }
    'src/views/css_/pseudo_class_befor_marker_selection_line_letter.vue': {
      routes:
        | '/css_/pseudo_class_befor_marker_selection_line_letter'
      views:
        | never
    }
    'src/views/css_/pseudo_class_checked.vue': {
      routes:
        | '/css_/pseudo_class_checked'
      views:
        | never
    }
    'src/views/css_/pseudo_class_child.vue': {
      routes:
        | '/css_/pseudo_class_child'
      views:
        | never
    }
    'src/views/css_/pseudo_class_enabled.vue': {
      routes:
        | '/css_/pseudo_class_enabled'
      views:
        | never
    }
    'src/views/css_/pseudo_class_focus.vue': {
      routes:
        | '/css_/pseudo_class_focus'
      views:
        | never
    }
    'src/views/css_/pseudo_class_focus_within.vue': {
      routes:
        | '/css_/pseudo_class_focus_within'
      views:
        | never
    }
    'src/views/css_/pseudo_class_has+.vue': {
      routes:
        | '/css_/pseudo_class_has+'
      views:
        | never
    }
    'src/views/css_/pseudo_class_not_has.vue': {
      routes:
        | '/css_/pseudo_class_not_has'
      views:
        | never
    }
    'src/views/css_/pseudo_class_only.vue': {
      routes:
        | '/css_/pseudo_class_only'
      views:
        | never
    }
    'src/views/css_/pseudo_class_required.vue': {
      routes:
        | '/css_/pseudo_class_required'
      views:
        | never
    }
    'src/views/css_/pseudo_class_type.vue': {
      routes:
        | '/css_/pseudo_class_type'
      views:
        | never
    }
    'src/views/css_/pseudo_class_valid.vue': {
      routes:
        | '/css_/pseudo_class_valid'
      views:
        | never
    }
    'src/views/css_/sequence.vue': {
      routes:
        | '/css_/sequence'
      views:
        | never
    }
    'src/views/css_/toggle_btn.vue': {
      routes:
        | '/css_/toggle_btn'
      views:
        | never
    }
    'src/views/css_/vis-a-vis.vue': {
      routes:
        | '/css_/vis-a-vis'
      views:
        | never
    }
    'src/views/demo/address_resolution.vue': {
      routes:
        | '/demo/address_resolution'
      views:
        | never
    }
    'src/views/demo/calendar.vue': {
      routes:
        | '/demo/calendar'
      views:
        | never
    }
    'src/views/demo/dingding.vue': {
      routes:
        | '/demo/dingding'
      views:
        | never
    }
    'src/views/demo/dom_to_img.vue': {
      routes:
        | '/demo/dom_to_img'
      views:
        | never
    }
    'src/views/demo/goods_car.vue': {
      routes:
        | '/demo/goods_car'
      views:
        | never
    }
    'src/views/demo/goods_spec.vue': {
      routes:
        | '/demo/goods_spec'
      views:
        | never
    }
    'src/views/demo/grape.vue': {
      routes:
        | '/demo/grape'
      views:
        | never
    }
    'src/views/demo/img_base64.vue': {
      routes:
        | '/demo/img_base64'
      views:
        | never
    }
    'src/views/demo/monaco-editor.vue': {
      routes:
        | '/demo/monaco-editor'
      views:
        | never
    }
    'src/views/demo/qr_code.vue': {
      routes:
        | '/demo/qr_code'
      views:
        | never
    }
    'src/views/demo/scan-code.vue': {
      routes:
        | '/demo/scan-code'
      views:
        | never
    }
    'src/views/demo/short_video.vue': {
      routes:
        | '/demo/short_video'
      views:
        | never
    }
    'src/views/demo/spark-ai.vue': {
      routes:
        | '/demo/spark-ai'
      views:
        | never
    }
    'src/views/demo/spin_swiper.vue': {
      routes:
        | '/demo/spin_swiper'
      views:
        | never
    }
    'src/views/demo/taskbar-transition-animation.vue': {
      routes:
        | '/demo/taskbar-transition-animation'
      views:
        | never
    }
    'src/views/demo/to_chinese_number.vue': {
      routes:
        | '/demo/to_chinese_number'
      views:
        | never
    }
    'src/views/demo/viewport-transition.vue': {
      routes:
        | '/demo/viewport-transition'
      views:
        | never
    }
    'src/views/echarts/basics.vue': {
      routes:
        | '/echarts/basics'
      views:
        | never
    }
    'src/views/echarts/horizontal_column_chart.vue': {
      routes:
        | '/echarts/horizontal_column_chart'
      views:
        | never
    }
    'src/views/echarts/map_of_china.vue': {
      routes:
        | '/echarts/map_of_china'
      views:
        | never
    }
    'src/views/echarts/qujin.vue': {
      routes:
        | '/echarts/qujin'
      views:
        | never
    }
    'src/views/echarts/series.vue': {
      routes:
        | '/echarts/series'
      views:
        | never
    }
    'src/views/echarts/sort.vue': {
      routes:
        | '/echarts/sort'
      views:
        | never
    }
    'src/views/echarts/title&position.vue': {
      routes:
        | '/echarts/title&position'
      views:
        | never
    }
    'src/views/echarts/weather.vue': {
      routes:
        | '/echarts/weather'
      views:
        | never
    }
    'src/views/echarts/wordcloud.vue': {
      routes:
        | '/echarts/wordcloud'
      views:
        | never
    }
    'src/views/echarts/xaxis.vue': {
      routes:
        | '/echarts/xaxis'
      views:
        | never
    }
    'src/views/echarts/yaxis.vue': {
      routes:
        | '/echarts/yaxis'
      views:
        | never
    }
    'src/views/es6/array-buffer.vue': {
      routes:
        | '/es6/array-buffer'
      views:
        | never
    }
    'src/views/es6/Iterator.vue': {
      routes:
        | '/es6/Iterator'
      views:
        | never
    }
    'src/views/es6/let.vue': {
      routes:
        | '/es6/let'
      views:
        | never
    }
    'src/views/es6/promise.vue': {
      routes:
        | '/es6/promise'
      views:
        | never
    }
    'src/views/es6/proxy&reflect.vue': {
      routes:
        | '/es6/proxy&reflect'
      views:
        | never
    }
    'src/views/es6/set&map.vue': {
      routes:
        | '/es6/set&map'
      views:
        | never
    }
    'src/views/es6/symbol.vue': {
      routes:
        | '/es6/symbol'
      views:
        | never
    }
    'src/views/es6/变量的解构赋值.vue': {
      routes:
        | '/es6/变量的解构赋值'
      views:
        | never
    }
    'src/views/es6/字符串新增方法.vue': {
      routes:
        | '/es6/字符串新增方法'
      views:
        | never
    }
    'src/views/es6/对象扩展.vue': {
      routes:
        | '/es6/对象扩展'
      views:
        | never
    }
    'src/views/es6/数组扩展.vue': {
      routes:
        | '/es6/数组扩展'
      views:
        | never
    }
    'src/views/es6/编程风格.vue': {
      routes:
        | '/es6/编程风格'
      views:
        | never
    }
    'src/views/js_/btoa.vue': {
      routes:
        | '/js_/btoa'
      views:
        | never
    }
    'src/views/js_/geolocation.vue': {
      routes:
        | '/js_/geolocation'
      views:
        | never
    }
    'src/views/js_/stop-array-foreach.vue': {
      routes:
        | '/js_/stop-array-foreach'
      views:
        | never
    }
    'src/views/js_/string.vue': {
      routes:
        | '/js_/string'
      views:
        | never
    }
    'src/views/js_/window-api.vue': {
      routes:
        | '/js_/window-api'
      views:
        | never
    }
    'src/views/less/&.vue': {
      routes:
        | '/less/&'
      views:
        | never
    }
    'src/views/less/function.vue': {
      routes:
        | '/less/function'
      views:
        | never
    }
    'src/views/less/gridding.vue': {
      routes:
        | '/less/gridding'
      views:
        | never
    }
    'src/views/less/hover_effect_1.vue': {
      routes:
        | '/less/hover_effect_1'
      views:
        | never
    }
    'src/views/less/if.vue': {
      routes:
        | '/less/if'
      views:
        | never
    }
    'src/views/less/inherit.vue': {
      routes:
        | '/less/inherit'
      views:
        | never
    }
    'src/views/less/list.vue': {
      routes:
        | '/less/list'
      views:
        | never
    }
    'src/views/less/math.vue': {
      routes:
        | '/less/math'
      views:
        | never
    }
    'src/views/less/mixin.vue': {
      routes:
        | '/less/mixin'
      views:
        | never
    }
    'src/views/less/props-merge.vue': {
      routes:
        | '/less/props-merge'
      views:
        | never
    }
    'src/views/less/var.vue': {
      routes:
        | '/less/var'
      views:
        | never
    }
    'src/views/motion/eg.vue': {
      routes:
        | '/motion/eg'
      views:
        | never
    }
    'src/views/scss/annotation.vue': {
      routes:
        | '/scss/annotation'
      views:
        | never
    }
    'src/views/scss/each.vue': {
      routes:
        | '/scss/each'
      views:
        | never
    }
    'src/views/scss/for.vue': {
      routes:
        | '/scss/for'
      views:
        | never
    }
    'src/views/scss/if&for.vue': {
      routes:
        | '/scss/if&for'
      views:
        | never
    }
    'src/views/scss/mix-in.vue': {
      routes:
        | '/scss/mix-in'
      views:
        | never
    }
    'src/views/scss/mixin.vue': {
      routes:
        | '/scss/mixin'
      views:
        | never
    }
    'src/views/scss/random-color.vue': {
      routes:
        | '/scss/random-color'
      views:
        | never
    }
    'src/views/scss/var.vue': {
      routes:
        | '/scss/var'
      views:
        | never
    }
    'src/views/scss/while.vue': {
      routes:
        | '/scss/while'
      views:
        | never
    }
    'src/views/scss/占位符百分号.vue': {
      routes:
        | '/scss/占位符百分号'
      views:
        | never
    }
    'src/views/scss/属性嵌套.vue': {
      routes:
        | '/scss/属性嵌套'
      views:
        | never
    }
    'src/views/scss/继承.vue': {
      routes:
        | '/scss/继承'
      views:
        | never
    }
    'src/views/swiper/base.vue': {
      routes:
        | '/swiper/base'
      views:
        | never
    }
    'src/views/three-js/amf.vue': {
      routes:
        | '/three-js/amf'
      views:
        | never
    }
    'src/views/three-js/axis.vue': {
      routes:
        | '/three-js/axis'
      views:
        | never
    }
    'src/views/three-js/base.vue': {
      routes:
        | '/three-js/base'
      views:
        | never
    }
    'src/views/three-js/first.vue': {
      routes:
        | '/three-js/first'
      views:
        | never
    }
    'src/views/three-js/hdr.vue': {
      routes:
        | '/three-js/hdr'
      views:
        | never
    }
    'src/views/three-js/obj.vue': {
      routes:
        | '/three-js/obj'
      views:
        | never
    }
    'src/views/three-js/textureLoader.vue': {
      routes:
        | '/three-js/textureLoader'
      views:
        | never
    }
    'src/views/vue/async-component.vue': {
      routes:
        | '/vue/async-component'
      views:
        | never
    }
    'src/views/vue/built-in_comp_transition.vue': {
      routes:
        | '/vue/built-in_comp_transition'
      views:
        | never
    }
    'src/views/vue/built-in_comp-keep-alive.vue': {
      routes:
        | '/vue/built-in_comp-keep-alive'
      views:
        | never
    }
    'src/views/vue/built-in_comp-teleport.vue': {
      routes:
        | '/vue/built-in_comp-teleport'
      views:
        | never
    }
    'src/views/vue/built-in_comp-transitiongroup.vue': {
      routes:
        | '/vue/built-in_comp-transitiongroup'
      views:
        | never
    }
    'src/views/vue/class_style.vue': {
      routes:
        | '/vue/class_style'
      views:
        | never
    }
    'src/views/vue/comp_message_parent_child.vue': {
      routes:
        | '/vue/comp_message_parent_child'
      views:
        | never
    }
    'src/views/vue/comp_message_v-model.vue': {
      routes:
        | '/vue/comp_message_v-model'
      views:
        | never
    }
    'src/views/vue/comp_message-provide.vue': {
      routes:
        | '/vue/comp_message-provide'
      views:
        | never
    }
    'src/views/vue/comp_message-ref.vue': {
      routes:
        | '/vue/comp_message-ref'
      views:
        | never
    }
    'src/views/vue/component_base.vue': {
      routes:
        | '/vue/component_base'
      views:
        | never
    }
    'src/views/vue/composable_apis.vue': {
      routes:
        | '/vue/composable_apis'
      views:
        | never
    }
    'src/views/vue/composite_functions.vue': {
      routes:
        | '/vue/composite_functions'
      views:
        | never
    }
    'src/views/vue/computed.vue': {
      routes:
        | '/vue/computed'
      views:
        | never
    }
    'src/views/vue/custom_instruction.vue': {
      routes:
        | '/vue/custom_instruction'
      views:
        | never
    }
    'src/views/vue/event.vue': {
      routes:
        | '/vue/event'
      views:
        | never
    }
    'src/views/vue/form_input.vue': {
      routes:
        | '/vue/form_input'
      views:
        | never
    }
    'src/views/vue/life_cycle.vue': {
      routes:
        | '/vue/life_cycle'
      views:
        | never
    }
    'src/views/vue/list.vue': {
      routes:
        | '/vue/list'
      views:
        | never
    }
    'src/views/vue/modifier.vue': {
      routes:
        | '/vue/modifier'
      views:
        | never
    }
    'src/views/vue/plug-in.vue': {
      routes:
        | '/vue/plug-in'
      views:
        | never
    }
    'src/views/vue/reactive_base.vue': {
      routes:
        | '/vue/reactive_base'
      views:
        | never
    }
    'src/views/vue/reactive_theory.vue': {
      routes:
        | '/vue/reactive_theory'
      views:
        | never
    }
    'src/views/vue/template.vue': {
      routes:
        | '/vue/template'
      views:
        | never
    }
    'src/views/vue/template_use.vue': {
      routes:
        | '/vue/template_use'
      views:
        | never
    }
    'src/views/vue/watch.vue': {
      routes:
        | '/vue/watch'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
