packages:
  - packages/*
  - vue/*
  - vue-latest/*
  - vue3/*
  - vue3-mini/*
  - vue3.3/*
  - vue3.4/*
  - vue3.5/*

catalog:
  '@amap/amap-jsapi-loader': ^1.0.1
  '@codemirror/lang-html': ^6.4.7
  '@codemirror/lang-javascript': ^6.2.1
  '@codemirror/lang-json': ^6.0.1
  '@codemirror/lang-vue': ^0.1.3
  '@codemirror/theme-one-dark': ^6.1.2
  '@tsconfig/node18': ^18.2.2
  '@tsconfig/node22': ^22.0.2
  '@types/crypto-js': ^4.2.2
  '@types/jsdom': ^21.1.6
  '@types/mockjs': ^1.0.10
  '@types/node': ^22.18.11
  '@vicons/ionicons4': ^0.12.0
  '@vitejs/plugin-basic-ssl': ^1.1.0
  '@vitejs/plugin-vue': ^6.0.1
  '@vitejs/plugin-vue-jsx': ^5.1.1
  '@vue/eslint-config-prettier': ^10.2.0
  '@vue/eslint-config-typescript': ^14.6.0
  '@vue/test-utils': ^2.4.3
  '@vue/tsconfig': ^0.8.1
  '@vueuse/core': ^10.7.2
  address-smart-parse: ^3.0.3
  codemirror: ^6.0.1
  crypto-js: ^4.1.1
  easyqrcodejs: ^4.6.1
  echarts: ^5.5.1
  echarts-wordcloud: ^2.1.0
  eslint: ^9.37.0
  eslint-plugin-vue: ~10.5.0
  highcharts: ^11.4.8
  html2canvas: ^1.4.1
  html5-qrcode: ^2.3.8
  jiti: ^2.6.1
  jsdom: ^23.0.1
  less: ^4.2.0
  lodash-es: ^4.17.21
  mockjs: ^1.1.0
  monaco-editor: ^0.52.2
  motion-v: ^1.7.0
  naive-ui: ^2.37.0
  npm-run-all2: ^8.0.4
  pinia: ^3.0.4
  prettier: 3.6.2
  sass: ^1.69.7
  swiper: ^11.1.4
  three: ^0.140.2
  typescript: ~5.9.0
  unplugin-vue-router: ^0.17.1
  vite: ^7.1.11
  vite-plugin-pages: ^0.32.3
  vite-plugin-vue-devtools: ^8.0.3
  vitest: ^1.0.4
  vue-codemirror: ^6.1.1
  vue-router: ^4.6.3
  vue-tsc: ^3.1.1
